# docker run -d -p 80:8080 -p 443:8443 jetty
version: '3'
services:
    redis:
        container_name: redis   
        build: ./redis/
        ports:
            - "6379:6379"

    jetty_1:
        container_name: jetty_1
        hostname: jetty_1
        image: jetty:9.3.20
        depends_on:
            - redis
        tty: true
        links:
            - redis
        volumes:
            - ./jetty/webapps:/var/lib/jetty/webapps
            - ./jetty/ext:/usr/local/jetty/lib/ext

    jetty_2:
        container_name: jetty_2
        hostname: jetty_2
        image: jetty:9.3.20
        depends_on:
            - redis
        links:
            - redis
        tty: true
        volumes:
            - ./jetty/webapps:/var/lib/jetty/webapps
            - ./jetty/ext:/usr/local/jetty/lib/ext

    haproxy:
        container_name: haproxy
        image: haproxy
        depends_on:
            - redis
            - jetty_1 
            - jetty_2
        volumes:
            - ./haproxy/conf:/usr/local/etc/haproxy
        ports:
            - "8080:8080"
            - "8082:8082"
